export const AVAILABLE_COLORS = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Graphite", hex: "#383838" },
  { name: "Midnight Blue", hex: "#191970" },
  { name: "Starlight", hex: "#F8F9EC" },
  { name: "Red", hex: "#FF0000" },
  { name: "Rose Gold", hex: "#B76E79" },
  { name: "Space Gray", hex: "#717378" },
  { name: "Alpine Green", hex: "#224A32" },
  { name: "Sierra Blue", hex: "#69ABCE" },
  { name: "Deep Purple", hex: "#4B4357" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Coral", hex: "#FF7F50" },
  { name: "Teal", hex: "#008080" },
  { name: "Navy", hex: "#000080" },
  { name: "Olive", hex: "#808000" },
  { name: "Maroon", hex: "#800000" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Lavender", hex: "#E6E6FA" },
  { name: "Plum", hex: "#DDA0DD" },
  { name: "Peach", hex: "#FFDAB9" },
  { name: "Cyan", hex: "#00FFFF" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Indigo", hex: "#4B0082" },
  { name: "Violet", hex: "#EE82EE" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Platinum", hex: "#E5E4E2" },
  { name: "Bronze", hex: "#CD7F32" },
  { name: "Champagne", hex: "#F7E7CE" },
  { name: "Charcoal", hex: "#36454F" },
  { name: "Crimson", hex: "#DC143C" },
  { name: "Ruby", hex: "#E0115F" },
  { name: "Sapphire", hex: "#0F52BA" },
  { name: "Emerald", hex: "#50C878" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Aqua", hex: "#00FFFF" },
  { name: "Mustard", hex: "#FFDB58" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Ivory", hex: "#FFFFF0" },
  { name: "Slate", hex: "#708090" },
  { name: "Sky Blue", hex: "#87CEEB" },
  { name: "Forest Green", hex: "#228B22" },
  { name: "Sunset Orange", hex: "#FD5E53" },
];
